任何函数式接口都不允许抛出受检查异常。如果你需要lambda表达式来抛出异常，有两种办法：定义一个自己的函数式接口，并声明受检查异常，或者把lambda包在一个try/catch中


为什么不支持受检查的异常呢？
因为大多数的函数式接口都未声明抛出异常！